# Generated by Django 2.0.1 on 2018-04-20 06:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('online_test', '0006_auto_20180420_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', model_utils.fields.StatusField(choices=[('Upcoming', 'Upcoming'), ('Running', 'Running'), ('Halted', 'Halted'), ('History', 'History')], default='Upcoming', max_length=100, no_check_for_status=True)),
                ('joined_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Student')),
            ],
        ),
    ]
