# Generated by Django 2.0.1 on 2018-04-13 08:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(default='VWUtjS2chrlQ', max_length=50, unique=True, verbose_name='test id')),
                ('title', models.CharField(help_text='Enter the test title', max_length=100, unique=True, verbose_name='test name')),
                ('url', models.SlugField(blank=True, help_text='Enter the url for the test', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Test description', max_length=300, verbose_name='test description')),
                ('instructions', models.CharField(blank=True, help_text='Test instructions', max_length=500, verbose_name='instructions')),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('draft', models.BooleanField(default=True, help_text='Uncheck to launch the test')),
            ],
            options={
                'verbose_name': 'test',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='part name')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Enter the question', max_length=1000)),
                ('figure', models.ImageField(blank=True, upload_to='diagrams/')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Exam')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Part')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', model_utils.fields.StatusField(choices=[('single_choice_correct_type', 'single_choice_correct_type'), ('multiple_choice_correct_type', 'multiple_choice_correct_type'), ('integer_answer_type', 'integer_answer_type')], default='single_choice_correct_type', max_length=100, no_check_for_status=True)),
                ('positive_marks', models.IntegerField(help_text='Positive Marks')),
                ('negative_marks', models.IntegerField(help_text='Negative Marks')),
                ('section_instructions', models.CharField(blank=True, help_text='Enter instructions for the section', max_length=1000)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Exam')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Part')),
            ],
        ),
        migrations.CreateModel(
            name='SingleChoiceCorrect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_1', models.CharField(max_length=50, verbose_name='Choice 1')),
                ('choice_2', models.CharField(max_length=50, verbose_name='Choice 1')),
                ('choice_3', models.CharField(max_length=50, verbose_name='Choice 1')),
                ('choice_4', models.CharField(max_length=50, verbose_name='Choice 1')),
                ('correct_choice', model_utils.fields.StatusField(choices=[('Choice-1', 'Choice-1'), ('Choice-2', 'Choice-2'), ('Choice-3', 'Choice-3'), ('Choice-4', 'Choice-4')], default='Choice-1', max_length=100, no_check_for_status=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Section'),
        ),
    ]
