# Generated by Django 2.0.1 on 2018-02-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=50, unique=True, verbose_name='test id')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='test name')),
                ('url', models.SlugField(max_length=100)),
                ('description', models.CharField(max_length=300, verbose_name='test description')),
                ('instructions', models.CharField(max_length=500, verbose_name='instructions')),
            ],
            options={
                'verbose_name': 'test name',
            },
        ),
    ]
