# Generated by Django 2.0.1 on 2018-02-09 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='part name')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Enter the question', max_length=1000)),
                ('figure', models.ImageField(blank=True, upload_to='diagrams/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'test'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.CharField(blank=True, help_text='Test description', max_length=300, verbose_name='test description'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='instructions',
            field=models.CharField(blank=True, help_text='Test instructions', max_length=500, verbose_name='instructions'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='test_id',
            field=models.CharField(default='Eu9Y7d', max_length=50, unique=True, verbose_name='test id'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(help_text='Enter the test title', max_length=100, unique=True, verbose_name='test name'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='url',
            field=models.SlugField(blank=True, help_text='Enter the url for the test', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Exam'),
        ),
        migrations.AddField(
            model_name='question',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Part'),
        ),
        migrations.AddField(
            model_name='part',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Exam'),
        ),
    ]
