# Generated by Django 2.0.1 on 2018-06-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='test_completed',
            field=models.BooleanField(default=False),
        ),
    ]
