# Generated by Django 2.0.1 on 2018-04-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='test_id',
            field=models.CharField(default='D221mFFXXVWZ', max_length=50, unique=True, verbose_name='test id'),
        ),
        migrations.AlterField(
            model_name='singlechoicecorrect',
            name='choice_2',
            field=models.CharField(max_length=50, verbose_name='Choice 2'),
        ),
        migrations.AlterField(
            model_name='singlechoicecorrect',
            name='choice_3',
            field=models.CharField(max_length=50, verbose_name='Choice 3'),
        ),
        migrations.AlterField(
            model_name='singlechoicecorrect',
            name='choice_4',
            field=models.CharField(max_length=50, verbose_name='Choice 4'),
        ),
    ]
