# Generated by Django 2.0.5 on 2018-06-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0002_exam_test_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section_type',
        ),
    ]
