# Generated by Django 2.0.1 on 2018-02-10 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0002_auto_20180209_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='exam',
            name='draft',
            field=models.BooleanField(default=True, help_text='Uncheck to launch the test'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='test_id',
            field=models.CharField(default='5wOriz', max_length=50, unique=True, verbose_name='test id'),
        ),
    ]
