# Generated by Django 2.0.1 on 2018-04-14 11:25

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0002_auto_20180413_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='test_id',
            field=models.CharField(default='3y8TlhgifsyY', max_length=50, unique=True, verbose_name='test id'),
        ),
        migrations.AlterField(
            model_name='question',
            name='part',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Physics', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='negative_marks',
            field=models.IntegerField(help_text='Example: -1'),
        ),
        migrations.AlterField(
            model_name='section',
            name='part',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Physics', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='positive_marks',
            field=models.IntegerField(help_text='Example: +4'),
        ),
    ]
