# Generated by Django 2.0.1 on 2018-04-19 10:01

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0003_auto_20180414_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('test_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_username', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full Name', max_length=50)),
                ('batch', model_utils.fields.StatusField(choices=[('11-Studying', '11-Studying'), ('12-Studying', '12-Studying'), ('12-Pass', '12-Pass'), ('other', 'other')], default='11-Studying', max_length=100, no_check_for_status=True)),
                ('Address', models.CharField(blank=True, max_length=200)),
                ('joined_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='part',
            name='exam',
        ),
        migrations.AlterField(
            model_name='exam',
            name='test_id',
            field=models.CharField(default='QZy3N9X9PAz2', max_length=50, unique=True, verbose_name='test id'),
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.AddField(
            model_name='result',
            name='student_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Student'),
        ),
        migrations.AddField(
            model_name='result',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='online_test.Exam'),
        ),
    ]
