# Generated by Django 2.0.1 on 2018-02-13 10:52

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0003_auto_20180210_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', model_utils.fields.StatusField(choices=[('single-choice-correct-type', 'single-choice-correct-type'), ('multiple-choice-correct-type', 'multiple-choice-correct-type'), ('integer-answer-type', 'integer-answer-type')], default='single-choice-correct-type', max_length=100, no_check_for_status=True)),
                ('section_instructions', models.CharField(blank=True, help_text='Enter instructions for the section', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='exam',
            name='test_id',
            field=models.CharField(default='0k0rt9', max_length=50, unique=True, verbose_name='test id'),
        ),
        migrations.AddField(
            model_name='section',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Exam'),
        ),
        migrations.AddField(
            model_name='section',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Part'),
        ),
    ]
