# Generated by Django 2.0.1 on 2018-06-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0003_question_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='serial',
            field=models.PositiveIntegerField(),
        ),
    ]
