# Generated by Django 2.0.5 on 2018-06-12 10:39

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0003_remove_section_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_type',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='single_choice_correct_type', max_length=100, no_check_for_status=True),
        ),
    ]
