# Generated by Django 2.0.1 on 2018-06-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0004_auto_20180612_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechoicecorrect',
            name='correct_choice',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20),
        ),
    ]
