# Generated by Django 2.0.1 on 2018-04-20 06:53

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0004_auto_20180419_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='draft',
        ),
        migrations.AddField(
            model_name='exam',
            name='published',
            field=models.BooleanField(default=False, help_text='Check to launch the test'),
        ),
        migrations.AddField(
            model_name='exam',
            name='test_type',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Free', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='test_id',
            field=models.CharField(default='McKkSeWfh0jU', max_length=50, unique=True, verbose_name='test id'),
        ),
    ]
