# Generated by Django 2.0.1 on 2018-02-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0004_auto_20180213_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section_type',
        ),
        migrations.AddField(
            model_name='section',
            name='status_type',
            field=models.CharField(blank=True, choices=[('single_choice_correct_type', 'single_choice_correct_type'), ('multiple_choice_correct_type', 'multiple_choice_correct_type'), ('integer_answer_type', 'integer_answer_type')], default='single_choice_correct_type', max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='test_id',
            field=models.CharField(default='n2jvpS', max_length=50, unique=True, verbose_name='test id'),
        ),
    ]
