# Generated by Django 2.0.5 on 2018-06-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0005_multiplechoicesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicesection',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='multiplechoicesection',
            name='part',
        ),
        migrations.AddField(
            model_name='section',
            name='per_question_positive_marks',
            field=models.IntegerField(default=1, help_text='Example: +1'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MultipleChoiceSection',
        ),
    ]
