# Generated by Django 2.0.1 on 2018-06-12 11:57

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0005_auto_20180612_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='serial',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='singlechoicecorrect',
            name='correct_choice',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Choice-1', max_length=100, no_check_for_status=True),
        ),
    ]
