# Generated by Django 2.0.1 on 2018-02-13 11:59

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0005_auto_20180213_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='test_id',
            field=models.CharField(default='nNHLLM', max_length=50, unique=True, verbose_name='test id'),
        ),
        migrations.AlterField(
            model_name='section',
            name='status_type',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='single_choice_correct_type', max_length=100, no_check_for_status=True),
        ),
    ]
