# Generated by Django 2.0.1 on 2018-06-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0006_auto_20180612_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechoicecorrect',
            name='correct_choice',
            field=models.CharField(choices=[('A', 'choice_1'), ('B', 'choice_2'), ('C', 'choice_3'), ('D', 'choice_4')], max_length=10),
        ),
    ]
