# Generated by Django 2.0.1 on 2018-02-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0006_auto_20180213_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='test_id',
            field=models.CharField(default='Nx3KeT', max_length=50, unique=True, verbose_name='test id'),
        ),
    ]
