# Generated by Django 2.0.1 on 2018-04-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0006_auto_20180420_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='test_id',
            field=models.CharField(default='NTUwJBxib7Zi', max_length=50, unique=True, verbose_name='test id'),
        ),
    ]
