# Generated by Django 2.0.5 on 2018-06-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0006_auto_20180612_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='per_question_positive_marks',
            new_name='per_option_positive_marks',
        ),
    ]
