# Generated by Django 2.0.1 on 2018-04-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0007_auto_20180420_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='test_id',
        ),
    ]
