# Generated by Django 2.0.1 on 2018-06-13 13:42

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0007_auto_20180612_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', jsonfield.fields.JSONField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Section')),
            ],
        ),
    ]
