# Generated by Django 2.0.1 on 2018-06-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0008_questionchoices'),
        ('online_test', '0007_auto_20180612_1641'),
    ]

    operations = [
    ]
