# Generated by Django 2.0.1 on 2018-06-16 06:33

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0009_merge_20180615_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoices',
            name='correct_choice',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionchoices',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_choices_question', to='online_test.Question'),
        ),
    ]
