# Generated by Django 2.0.5 on 2018-06-15 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0009_merge_20180615_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoices',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_choices_question', to='online_test.Question'),
        ),
    ]
