# Generated by Django 2.0.1 on 2018-02-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0010_auto_20180221_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.CharField(blank=True, help_text='The passage will appear before the question, if entered', max_length=1000),
        ),
        migrations.AddField(
            model_name='section',
            name='negative_marks',
            field=models.IntegerField(default=1, help_text='Negative Marks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='positive_marks',
            field=models.IntegerField(default=1, help_text='Positive Marks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='test_id',
            field=models.CharField(default='lzFX5uhwAFxj', max_length=50, unique=True, verbose_name='test id'),
        ),
    ]
