# Generated by Django 2.0.1 on 2018-05-01 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0010_auto_20180422_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='part name')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Exam')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_questions', to='online_test.Part'),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_questions', to='online_test.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='online_test.Part'),
        ),
    ]
