# Generated by Django 2.0.5 on 2018-06-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0010_auto_20180616_1203'),
        ('online_test', '0010_auto_20180615_1229'),
    ]

    operations = [
    ]
