# Generated by Django 2.0.1 on 2018-03-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0011_auto_20180228_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='test_id',
            field=models.CharField(default='QKCRuF6JC2Ev', max_length=50, unique=True, verbose_name='test id'),
        ),
    ]
