# Generated by Django 2.0 on 2019-03-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0011_merge_20180616_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.CharField(blank=True, help_text='Test description', max_length=2000, verbose_name='test description'),
        ),
    ]
