# Generated by Django 2.0.1 on 2018-03-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0012_auto_20180304_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='test_id',
            field=models.CharField(default='Q7vUqGo5aMWf', max_length=50, unique=True, verbose_name='test id'),
        ),
    ]
