# Generated by Django 2.0.1 on 2018-05-05 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0012_auto_20180501_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechoicecorrect',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singlechoicecorrect_question', to='online_test.Question'),
        ),
    ]
