# Generated by Django 2.0 on 2019-03-11 17:30

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0012_auto_20190310_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='progress_flags',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
