# Generated by Django 2.0.1 on 2018-04-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0013_auto_20180311_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='test_id',
            field=models.CharField(default='RXA6a72sptT0', max_length=50, unique=True, verbose_name='test id'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=50, verbose_name='part name'),
        ),
    ]
