# Generated by Django 2.0 on 2019-03-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0013_dynamic_progress_flags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamic',
            old_name='progress_flags',
            new_name='progress_state',
        ),
    ]
