# Generated by Django 2.0.5 on 2018-06-07 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0013_auto_20180505_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_1', models.CharField(max_length=50, verbose_name='Choice 1')),
                ('choice_2', models.CharField(max_length=50, verbose_name='Choice 2')),
                ('choice_3', models.CharField(max_length=50, verbose_name='Choice 3')),
                ('choice_4', models.CharField(max_length=50, verbose_name='Choice 4')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Question')),
            ],
        ),
    ]
