# Generated by Django 2.0.1 on 2018-04-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0014_auto_20180405_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='test_id',
            field=models.CharField(default='O8IziViKPLqW', max_length=50, unique=True, verbose_name='test id'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='part name'),
        ),
    ]
