# Generated by Django 2.0 on 2019-03-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0014_auto_20190316_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, help_text='Test description'),
        ),
    ]
