# Generated by Django 2.0.5 on 2018-06-08 11:12

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0015_auto_20180608_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamic',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='dynamic',
            name='selected',
        ),
        migrations.AddField(
            model_name='dynamic',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_test.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dynamic',
            name='test_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='online_test.Exam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='result_json',
            field=jsonfield.fields.JSONField(),
        ),
    ]
