# Generated by Django 2.0 on 2019-03-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0015_auto_20190316_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True, help_text='Test instructions', verbose_name='instructions'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(help_text='Enter the question'),
        ),
    ]
