# Generated by Django 2.0.5 on 2018-06-08 11:29

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0016_auto_20180608_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='progress',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
    ]
