# Generated by Django 2.0 on 2019-03-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0016_auto_20190316_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_instructions',
            field=models.TextField(blank=True, help_text='Enter instructions for the section'),
        ),
    ]
