# Generated by Django 2.0.5 on 2018-06-08 13:37

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0017_dynamic_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamic',
            old_name='student_id',
            new_name='student_username',
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='progress',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
