# Generated by Django 2.0.1 on 2018-06-08 13:36

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0017_dynamic_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='progress',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
