# Generated by Django 2.0.5 on 2018-06-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0018_auto_20180608_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamic',
            old_name='student_username',
            new_name='student_id',
        ),
    ]
