# Generated by Django 2.0.1 on 2018-06-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0019_auto_20180608_1919'),
        ('online_test', '0018_auto_20180608_1906'),
    ]

    operations = [
    ]
